version: 2

sphinx:
  configuration: ch08/first-python-package/docs/conf.py

formats:
  - htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: ch08/first-python-package
